version: '3'
services:
  database:
    image: postgres
    container_name: library-database
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: library
    ports:
      - '5434:5432'
