version: '3'
services:
  database:
    image: postgres
    container_name: library-database
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: library
    ports:
      - '5434:5432'
    volumes:
      - ./src/main/resources/sql/schema-tmp.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
