spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: spring_app
    password: test

logging:
  level:
    org.springframework.web: DEBUG
    Exposed: DEBUG

cron:
  basic: 0 0 0 * * *
  update-penalties: ${cron.basic}
  revoke-awaiting-resources: ${cron.basic}
  revoke-ebooks: ${cron.basic}
