spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: test

logging:
  level:
    org.springframework.web: DEBUG
    Exposed: DEBUG

cron:
  update-penalties: 0 0 0 * * *
  revoke-awaiting-resources: ${cron.update-penalties}
