### Get libraries
GET {{url}}/libraries

### Get books
GET {{url}}/books

### Get books filtered
GET {{url}}/books?search=sapkowski

### Get ebooks
GET {{url}}/ebooks

### Register user
POST {{url}}/users
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Nowak",
  "email": "{{$random.email}}",
  "login": "{{$random.alphabetic(10)}}",
  "password": "{{$random.alphanumeric(8)}}"
}

### Get user
GET {{url}}/users/{{userId}}

### Get user settings
GET {{url}}/users/{{userId}}/settings

### Get user storage
GET {{url}}/storage
