###
# @name Get libraries
GET http://localhost:8080/libraries

###
# @name Get books
GET http://localhost:8080/books

###
# @name Get ebooks
GET http://localhost:8080/ebooks

###
# @name Register user
POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Nowak",
  "email": "{{$random.email}}",
  "login": "{{$random.alphabetic(10)}}",
  "password": "{{$random.alphanumeric(8)}}"
}

###
# @name Get user
GET http://localhost:8080/users/{{userId}}

###
# @name Get user settings
GET http://localhost:8080/users/{{userId}}/settings

###
# @name Get user storage
GET http://localhost:8080/storage
